name: SpaceMine APK Yapici
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer ile APK Pisir
        uses: NiklasHygum/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.8
